### ISSUE TITLE
Does it support H264?

### ISSUE THREAD

**Issue by LucasDang** [julian-ladjani/GoogleWebRTC#1]
Due to network and some environment error, I could not build it.
Could you please help me to build a framework in m79 and support H264?

**Comment by julian-ladjani** [comment]
I think you can just use official releases from CocoaPods and use RTCVideoEncoderFactoryH264  and RTCVideoDecoderFactoryH264 to initialize RTCPeerConnectionFactory

https://cocoapods.org/pods/GoogleWebRTC

**Comment by LucasDang** [comment]
Thanks！
